version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: fedena-change-me
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: fedena-change-me
      MYSQL_PORT: 3306
      MYSQL_HOST: db
      RAILS_ENV: production
    volumes:
      - ".:/workdir"

